import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookiesStore = cookies();
  const theme = cookiesStore.get('theme')?.value;

  return (
    <html lang="en" className={`${theme || 'dark'}`}>
      <body className={inter.className}>{children}</body>
      <head>
        <link
          rel="icon"
          href={`${theme === 'dark' ? '/moon.svg' : '/sun.svg'}`}
          sizes="any"
        />
      </head>
    </html>
  );
}
